WIP Support Plone 5.2
kitconcept/kitconcept.solr pull request #17
Opened 2023-09-19 12:52 UTC by reekitconcept

2023-09-19 12:56 UTC, reekitconcept commented
WIP because... I cannot figure out how to run the tests with Plone 5.2 via plone meta.

https://github.com/plone/meta/issues/146 indicates that this cannot currently be done.

I cannot find any way to set this up. There is a way to use an alternate `constraints.txt` which is what we would need, but I cannot find any way to run two sets of tests, one with the original and one with the 5.2 constrainst. The test job or even the full yaml can be duplicated, but they will still use the same configuration from `meta.toml`. Am I overlooking something? Any insight is welcome.

2023-09-25 08:17 UTC, reekitconcept commented
Update on Plone 5.2.

The branch works with 5.2, a few caveats:

- I had to completely drop the dependency of plone.restapi to accomodate both Plone 5.2 and 6, this won't be a problem as soon as the new Plone 6 release requires this version only, until then we _may_ need to add the extra plone.restapi dependency to Plone 6 projects currently use the package.

- plone.meta does not support multiple versions but I added a separate github action

- the new testing framework seems to have version conflicts with Plone 5.2, I don't think this can be solved - I might be wrong - but in any case we won't add the old tests back, so right now with Plone 5.2 we do test the build but we don't actually run the tests, which is "good enough" at the moment.

2023-09-25 08:37 UTC, reekitconcept commented
Remark about the reindex helpers: I pushed the update about the reindex helpers here (to make them importable from projects, and use reindex as an upgrade step), so this can go into the next alpha release as well.

2023-09-26 02:44 UTC, ericof requested changes

2023-09-26 02:44 UTC, ericof commented on .github/workflows/test-plone-5.2.yml
> +      - name: Set up Python ${{ matrix.python-version }}
Please use https://github.com/plone/setup-plone instead of setup-python

2023-09-26 02:44 UTC, ericof commented on .github/workflows/test-plone-5.2.yml
> +      - uses: actions/checkout@v2
Bump action version to `v4`

2023-09-26 02:44 UTC, ericof commented on .github/workflows/test-plone-5.2.yml
> +      # test
Why do we have the workflow if we are not running the tests?

2023-09-27 10:56 UTC, reekitconcept commented on .github/workflows/test-plone-5.2.yml
> +      # test
At least it runs the install and checks that the dependencies are correct, which is something because that was also breaking earlier.

The main problem is that the test dependencies conflict for me with the Plone 5.2 requirements.

I'd like to run the test but @ericof is it possible to install pytests with Plone 5.2? I'm getting version conflicts. If this is something that is resolvable I'm glad to put more time into it, but it's just a waste of time if the answer is "no".

2023-09-29 15:11 UTC, reekitconcept commented
@ericof I would rely on your help to fix the version conflict for running the tests on Plone 5.2. However I'm also ok to make an alpha release without the tests, I have some upcoming changes anyway so we will definitely have yet another alpha. However we need a release for staging our project that will use this package with Plone 5.2

I leave it up to your consideration, either way (with or without tests) I'll follow up once we have the next alpha.

2023-10-10 14:41 UTC, ericof approved these changes
Merging without 5.2 tests

2023-10-10 14:41 UTC, merged